using System.Collections.Generic;

namespace OBD2Suite.Services
{
    public static class DtcDatabase
    {
        private static readonly Dictionary<string, string> _descriptions = new()
        {
            // P0xxx - Fuel and Air Metering
            { "P0001", "Fuel Volume Regulator Control Circuit/Open" },
            { "P0002", "Fuel Volume Regulator Control Circuit Range/Performance" },
            { "P0003", "Fuel Volume Regulator Control Circuit Low" },
            { "P0004", "Fuel Volume Regulator Control Circuit High" },
            { "P0010", "Intake Camshaft Position Actuator Circuit/Open (Bank 1)" },
            { "P0011", "Intake Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)" },
            { "P0012", "Intake Camshaft Position - Timing Over-Retarded (Bank 1)" },
            { "P0013", "Exhaust Camshaft Position Actuator Circuit/Open (Bank 1)" },
            { "P0014", "Exhaust Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)" },
            { "P0015", "Exhaust Camshaft Position - Timing Over-Retarded (Bank 1)" },
            { "P0016", "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)" },
            { "P0017", "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)" },
            { "P0018", "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor A)" },
            { "P0019", "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor B)" },
            { "P0020", "Intake Camshaft Position Actuator Circuit/Open (Bank 2)" },
            { "P0021", "Intake Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)" },
            { "P0030", "HO2S Heater Control Circuit (Bank 1 Sensor 1)" },
            { "P0031", "HO2S Heater Control Circuit Low (Bank 1 Sensor 1)" },
            { "P0032", "HO2S Heater Control Circuit High (Bank 1 Sensor 1)" },
            { "P0036", "HO2S Heater Control Circuit (Bank 1 Sensor 2)" },
            { "P0037", "HO2S Heater Control Circuit Low (Bank 1 Sensor 2)" },
            { "P0038", "HO2S Heater Control Circuit High (Bank 1 Sensor 2)" },
            { "P0051", "HO2S Heater Control Circuit Low (Bank 2 Sensor 1)" },
            { "P0052", "HO2S Heater Control Circuit High (Bank 2 Sensor 1)" },
            { "P0057", "HO2S Heater Control Circuit Low (Bank 2 Sensor 2)" },
            { "P0058", "HO2S Heater Control Circuit High (Bank 2 Sensor 2)" },
            { "P0068", "MAP/MAF - Throttle Position Correlation" },
            { "P0069", "Manifold Absolute Pressure - Barometric Pressure Correlation" },
            { "P0070", "Ambient Air Temperature Sensor Circuit" },
            { "P0071", "Ambient Air Temperature Sensor Range/Performance" },
            { "P0087", "Fuel Rail/System Pressure - Too Low" },
            { "P0088", "Fuel Rail/System Pressure - Too High" },
            { "P0089", "Fuel Pressure Regulator 1 Performance" },
            { "P0090", "Fuel Pressure Regulator 1 Control Circuit" },
            { "P0091", "Fuel Pressure Regulator 1 Control Circuit Low" },
            { "P0092", "Fuel Pressure Regulator 1 Control Circuit High" },
            { "P0093", "Fuel System Leak Detected - Large Leak" },
            { "P0094", "Fuel System Leak Detected - Small Leak" },
            { "P0095", "Intake Air Temperature Sensor 2 Circuit" },
            { "P0096", "Intake Air Temperature Sensor 2 Circuit Range/Performance" },
            { "P0097", "Intake Air Temperature Sensor 2 Circuit Low" },
            { "P0098", "Intake Air Temperature Sensor 2 Circuit High" },
            { "P0099", "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic" },
            { "P0100", "Mass or Volume Air Flow Circuit Malfunction" },
            { "P0101", "Mass or Volume Air Flow Circuit Range/Performance Problem" },
            { "P0102", "Mass or Volume Air Flow Circuit Low Input" },
            { "P0103", "Mass or Volume Air Flow Circuit High Input" },
            { "P0104", "Mass or Volume Air Flow Circuit Intermittent" },
            { "P0105", "Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction" },
            { "P0106", "Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem" },
            { "P0107", "Manifold Absolute Pressure/Barometric Pressure Circuit Low Input" },
            { "P0108", "Manifold Absolute Pressure/Barometric Pressure Circuit High Input" },
            { "P0109", "Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent" },
            { "P0110", "Intake Air Temperature Circuit Malfunction" },
            { "P0111", "Intake Air Temperature Circuit Range/Performance Problem" },
            { "P0112", "Intake Air Temperature Circuit Low Input" },
            { "P0113", "Intake Air Temperature Circuit High Input" },
            { "P0114", "Intake Air Temperature Circuit Intermittent" },
            { "P0115", "Engine Coolant Temperature Circuit Malfunction" },
            { "P0116", "Engine Coolant Temperature Circuit Range/Performance Problem" },
            { "P0117", "Engine Coolant Temperature Circuit Low Input" },
            { "P0118", "Engine Coolant Temperature Circuit High Input" },
            { "P0119", "Engine Coolant Temperature Circuit Intermittent" },
            { "P0120", "Throttle/Pedal Position Sensor/Switch A Circuit Malfunction" },
            { "P0121", "Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance Problem" },
            { "P0122", "Throttle/Pedal Position Sensor/Switch A Circuit Low Input" },
            { "P0123", "Throttle/Pedal Position Sensor/Switch A Circuit High Input" },
            { "P0124", "Throttle/Pedal Position Sensor/Switch A Circuit Intermittent" },
            { "P0125", "Insufficient Coolant Temperature for Closed Loop Fuel Control" },
            { "P0126", "Insufficient Coolant Temperature for Stable Operation" },
            { "P0128", "Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)" },
            { "P0130", "O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)" },
            { "P0131", "O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)" },
            { "P0132", "O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)" },
            { "P0133", "O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)" },
            { "P0134", "O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)" },
            { "P0135", "O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)" },
            { "P0136", "O2 Sensor Circuit Malfunction (Bank 1 Sensor 2)" },
            { "P0137", "O2 Sensor Circuit Low Voltage (Bank 1 Sensor 2)" },
            { "P0138", "O2 Sensor Circuit High Voltage (Bank 1 Sensor 2)" },
            { "P0139", "O2 Sensor Circuit Slow Response (Bank 1 Sensor 2)" },
            { "P0140", "O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 2)" },
            { "P0141", "O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)" },
            { "P0150", "O2 Sensor Circuit Malfunction (Bank 2 Sensor 1)" },
            { "P0151", "O2 Sensor Circuit Low Voltage (Bank 2 Sensor 1)" },
            { "P0152", "O2 Sensor Circuit High Voltage (Bank 2 Sensor 1)" },
            { "P0153", "O2 Sensor Circuit Slow Response (Bank 2 Sensor 1)" },
            { "P0154", "O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 1)" },
            { "P0155", "O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 1)" },
            { "P0156", "O2 Sensor Circuit Malfunction (Bank 2 Sensor 2)" },
            { "P0157", "O2 Sensor Circuit Low Voltage (Bank 2 Sensor 2)" },
            { "P0158", "O2 Sensor Circuit High Voltage (Bank 2 Sensor 2)" },
            { "P0159", "O2 Sensor Circuit Slow Response (Bank 2 Sensor 2)" },
            { "P0160", "O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 2)" },
            { "P0161", "O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 2)" },
            { "P0170", "Fuel Trim Malfunction (Bank 1)" },
            { "P0171", "System Too Lean (Bank 1)" },
            { "P0172", "System Too Rich (Bank 1)" },
            { "P0173", "Fuel Trim Malfunction (Bank 2)" },
            { "P0174", "System Too Lean (Bank 2)" },
            { "P0175", "System Too Rich (Bank 2)" },
            { "P0176", "Fuel Composition Sensor Circuit Malfunction" },
            { "P0180", "Fuel Temperature Sensor A Circuit Malfunction" },
            { "P0181", "Fuel Temperature Sensor A Circuit Range/Performance" },
            { "P0182", "Fuel Temperature Sensor A Circuit Low Input" },
            { "P0183", "Fuel Temperature Sensor A Circuit High Input" },
            { "P0190", "Fuel Rail Pressure Sensor Circuit Malfunction" },
            { "P0191", "Fuel Rail Pressure Sensor Circuit Range/Performance" },
            { "P0192", "Fuel Rail Pressure Sensor Circuit Low Input" },
            { "P0193", "Fuel Rail Pressure Sensor Circuit High Input" },
            { "P0194", "Fuel Rail Pressure Sensor Circuit Intermittent" },
            { "P0195", "Engine Oil Temperature Sensor Malfunction" },
            { "P0196", "Engine Oil Temperature Sensor Range/Performance" },
            { "P0197", "Engine Oil Temperature Sensor Low" },
            { "P0198", "Engine Oil Temperature Sensor High" },
            { "P0199", "Engine Oil Temperature Sensor Intermittent" },
            { "P0200", "Injector Circuit Malfunction" },
            { "P0201", "Injector Circuit Malfunction - Cylinder 1" },
            { "P0202", "Injector Circuit Malfunction - Cylinder 2" },
            { "P0203", "Injector Circuit Malfunction - Cylinder 3" },
            { "P0204", "Injector Circuit Malfunction - Cylinder 4" },
            { "P0205", "Injector Circuit Malfunction - Cylinder 5" },
            { "P0206", "Injector Circuit Malfunction - Cylinder 6" },
            { "P0207", "Injector Circuit Malfunction - Cylinder 7" },
            { "P0208", "Injector Circuit Malfunction - Cylinder 8" },
            { "P0217", "Engine Overtemperature Condition" },
            { "P0218", "Transmission Over Temperature Condition" },
            { "P0219", "Engine Overspeed Condition" },
            { "P0220", "Throttle/Pedal Position Sensor/Switch B Circuit Malfunction" },
            { "P0221", "Throttle/Pedal Position Sensor/Switch B Circuit Range/Performance Problem" },
            { "P0222", "Throttle/Pedal Position Sensor/Switch B Circuit Low Input" },
            { "P0223", "Throttle/Pedal Position Sensor/Switch B Circuit High Input" },
            { "P0224", "Throttle/Pedal Position Sensor/Switch B Circuit Intermittent" },
            { "P0230", "Fuel Pump Primary Circuit Malfunction" },
            { "P0231", "Fuel Pump Secondary Circuit Low" },
            { "P0232", "Fuel Pump Secondary Circuit High" },
            { "P0234", "Turbocharger Overboost Condition" },
            { "P0235", "Turbocharger Boost Sensor A Circuit Malfunction" },
            { "P0236", "Turbocharger Boost Sensor A Circuit Range/Performance" },
            { "P0237", "Turbocharger Boost Sensor A Circuit Low" },
            { "P0238", "Turbocharger Boost Sensor A Circuit High" },
            { "P0240", "Turbocharger Boost Sensor B Circuit Malfunction" },
            { "P0243", "Turbocharger Wastegate Solenoid A Malfunction" },
            { "P0244", "Turbocharger Wastegate Solenoid A Range/Performance" },
            { "P0245", "Turbocharger Wastegate Solenoid A Low" },
            { "P0246", "Turbocharger Wastegate Solenoid A High" },
            { "P0251", "Injection Pump Fuel Metering Control A Malfunction" },
            { "P0261", "Cylinder 1 Injector Circuit Low" },
            { "P0262", "Cylinder 1 Injector Circuit High" },
            { "P0263", "Cylinder 1 Contribution/Balance Fault" },
            { "P0264", "Cylinder 2 Injector Circuit Low" },
            { "P0265", "Cylinder 2 Injector Circuit High" },
            { "P0266", "Cylinder 2 Contribution/Balance Fault" },
            { "P0267", "Cylinder 3 Injector Circuit Low" },
            { "P0268", "Cylinder 3 Injector Circuit High" },
            { "P0269", "Cylinder 3 Contribution/Balance Fault" },
            { "P0270", "Cylinder 4 Injector Circuit Low" },
            { "P0271", "Cylinder 4 Injector Circuit High" },
            { "P0272", "Cylinder 4 Contribution/Balance Fault" },
            { "P0273", "Cylinder 5 Injector Circuit Low" },
            { "P0274", "Cylinder 5 Injector Circuit High" },
            { "P0275", "Cylinder 5 Contribution/Balance Fault" },
            { "P0276", "Cylinder 6 Injector Circuit Low" },
            { "P0277", "Cylinder 6 Injector Circuit High" },
            { "P0278", "Cylinder 6 Contribution/Balance Fault" },
            { "P0279", "Cylinder 7 Injector Circuit Low" },
            { "P0280", "Cylinder 7 Injector Circuit High" },
            { "P0281", "Cylinder 7 Contribution/Balance Fault" },
            { "P0282", "Cylinder 8 Injector Circuit Low" },
            { "P0283", "Cylinder 8 Injector Circuit High" },
            { "P0284", "Cylinder 8 Contribution/Balance Fault" },
            { "P0300", "Random/Multiple Cylinder Misfire Detected" },
            { "P0301", "Cylinder 1 Misfire Detected" },
            { "P0302", "Cylinder 2 Misfire Detected" },
            { "P0303", "Cylinder 3 Misfire Detected" },
            { "P0304", "Cylinder 4 Misfire Detected" },
            { "P0305", "Cylinder 5 Misfire Detected" },
            { "P0306", "Cylinder 6 Misfire Detected" },
            { "P0307", "Cylinder 7 Misfire Detected" },
            { "P0308", "Cylinder 8 Misfire Detected" },
            { "P0316", "Misfire Detected on Startup (First 1000 Revolutions)" },
            { "P0320", "Ignition/Distributor Engine Speed Input Circuit Malfunction" },
            { "P0321", "Ignition/Distributor Engine Speed Input Circuit Range/Performance" },
            { "P0322", "Ignition/Distributor Engine Speed Input Circuit No Signal" },
            { "P0323", "Ignition/Distributor Engine Speed Input Circuit Intermittent" },
            { "P0324", "Knock Control System Error" },
            { "P0325", "Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)" },
            { "P0326", "Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)" },
            { "P0327", "Knock Sensor 1 Circuit Low Input (Bank 1 or Single Sensor)" },
            { "P0328", "Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)" },
            { "P0329", "Knock Sensor 1 Circuit Input Intermittent (Bank 1 or Single Sensor)" },
            { "P0330", "Knock Sensor 2 Circuit Malfunction (Bank 2)" },
            { "P0331", "Knock Sensor 2 Circuit Range/Performance (Bank 2)" },
            { "P0332", "Knock Sensor 2 Circuit Low Input (Bank 2)" },
            { "P0333", "Knock Sensor 2 Circuit High Input (Bank 2)" },
            { "P0334", "Knock Sensor 2 Circuit Input Intermittent (Bank 2)" },
            { "P0335", "Crankshaft Position Sensor A Circuit Malfunction" },
            { "P0336", "Crankshaft Position Sensor A Circuit Range/Performance" },
            { "P0337", "Crankshaft Position Sensor A Circuit Low Input" },
            { "P0338", "Crankshaft Position Sensor A Circuit High Input" },
            { "P0339", "Crankshaft Position Sensor A Circuit Intermittent" },
            { "P0340", "Camshaft Position Sensor A Circuit Malfunction (Bank 1 or Single Sensor)" },
            { "P0341", "Camshaft Position Sensor A Circuit Range/Performance (Bank 1 or Single Sensor)" },
            { "P0342", "Camshaft Position Sensor A Circuit Low Input (Bank 1 or Single Sensor)" },
            { "P0343", "Camshaft Position Sensor A Circuit High Input (Bank 1 or Single Sensor)" },
            { "P0344", "Camshaft Position Sensor A Circuit Intermittent (Bank 1 or Single Sensor)" },
            { "P0345", "Camshaft Position Sensor A Circuit Malfunction (Bank 2)" },
            { "P0351", "Ignition Coil A Primary/Secondary Circuit Malfunction" },
            { "P0352", "Ignition Coil B Primary/Secondary Circuit Malfunction" },
            { "P0353", "Ignition Coil C Primary/Secondary Circuit Malfunction" },
            { "P0354", "Ignition Coil D Primary/Secondary Circuit Malfunction" },
            { "P0355", "Ignition Coil E Primary/Secondary Circuit Malfunction" },
            { "P0356", "Ignition Coil F Primary/Secondary Circuit Malfunction" },
            { "P0357", "Ignition Coil G Primary/Secondary Circuit Malfunction" },
            { "P0358", "Ignition Coil H Primary/Secondary Circuit Malfunction" },
            { "P0380", "Glow Plug/Heater Circuit A Malfunction" },
            { "P0381", "Glow Plug/Heater Indicator Circuit Malfunction" },
            { "P0382", "Glow Plug/Heater Circuit B Malfunction" },
            { "P0385", "Crankshaft Position Sensor B Circuit Malfunction" },
            { "P0386", "Crankshaft Position Sensor B Circuit Range/Performance" },
            { "P0400", "Exhaust Gas Recirculation Flow Malfunction" },
            { "P0401", "Exhaust Gas Recirculation Flow Insufficient Detected" },
            { "P0402", "Exhaust Gas Recirculation Flow Excessive Detected" },
            { "P0403", "Exhaust Gas Recirculation Circuit Malfunction" },
            { "P0404", "Exhaust Gas Recirculation Circuit Range/Performance" },
            { "P0405", "Exhaust Gas Recirculation Sensor A Circuit Low" },
            { "P0406", "Exhaust Gas Recirculation Sensor A Circuit High" },
            { "P0407", "Exhaust Gas Recirculation Sensor B Circuit Low" },
            { "P0408", "Exhaust Gas Recirculation Sensor B Circuit High" },
            { "P0410", "Secondary Air Injection System Malfunction" },
            { "P0411", "Secondary Air Injection System Incorrect Flow Detected" },
            { "P0412", "Secondary Air Injection System Switching Valve A Circuit Malfunction" },
            { "P0413", "Secondary Air Injection System Switching Valve A Circuit Open" },
            { "P0414", "Secondary Air Injection System Switching Valve A Circuit Shorted" },
            { "P0420", "Catalyst System Efficiency Below Threshold (Bank 1)" },
            { "P0421", "Warm Up Catalyst Efficiency Below Threshold (Bank 1)" },
            { "P0422", "Main Catalyst Efficiency Below Threshold (Bank 1)" },
            { "P0423", "Heated Catalyst Efficiency Below Threshold (Bank 1)" },
            { "P0424", "Heated Catalyst Temperature Below Threshold (Bank 1)" },
            { "P0430", "Catalyst System Efficiency Below Threshold (Bank 2)" },
            { "P0431", "Warm Up Catalyst Efficiency Below Threshold (Bank 2)" },
            { "P0432", "Main Catalyst Efficiency Below Threshold (Bank 2)" },
            { "P0433", "Heated Catalyst Efficiency Below Threshold (Bank 2)" },
            { "P0434", "Heated Catalyst Temperature Below Threshold (Bank 2)" },
            { "P0440", "Evaporative Emission Control System Malfunction" },
            { "P0441", "Evaporative Emission Control System Incorrect Purge Flow" },
            { "P0442", "Evaporative Emission Control System Leak Detected (small leak)" },
            { "P0443", "Evaporative Emission Control System Purge Control Valve Circuit Malfunction" },
            { "P0444", "Evaporative Emission Control System Purge Control Valve Circuit Open" },
            { "P0445", "Evaporative Emission Control System Purge Control Valve Circuit Shorted" },
            { "P0446", "Evaporative Emission Control System Vent Control Circuit Malfunction" },
            { "P0447", "Evaporative Emission Control System Vent Control Circuit Open" },
            { "P0448", "Evaporative Emission Control System Vent Control Circuit Shorted" },
            { "P0449", "Evaporative Emission System Vent Valve/Solenoid Circuit Malfunction" },
            { "P0450", "Evaporative Emission Control System Pressure Sensor Malfunction" },
            { "P0451", "Evaporative Emission Control System Pressure Sensor Range/Performance" },
            { "P0452", "Evaporative Emission Control System Pressure Sensor Low Input" },
            { "P0453", "Evaporative Emission Control System Pressure Sensor High Input" },
            { "P0454", "Evaporative Emission Control System Pressure Sensor Intermittent" },
            { "P0455", "Evaporative Emission Control System Leak Detected (gross leak)" },
            { "P0456", "Evaporative Emission Control System Leak Detected (very small leak)" },
            { "P0457", "Evaporative Emission Control System Leak Detected (fuel cap loose/off)" },
            { "P0458", "Evaporative Emission System Purge Control Valve Circuit Low" },
            { "P0459", "Evaporative Emission System Purge Control Valve Circuit High" },
            { "P0460", "Fuel Level Sensor Circuit Malfunction" },
            { "P0461", "Fuel Level Sensor Circuit Range/Performance" },
            { "P0462", "Fuel Level Sensor Circuit Low Input" },
            { "P0463", "Fuel Level Sensor Circuit High Input" },
            { "P0464", "Fuel Level Sensor Circuit Intermittent" },
            { "P0480", "Cooling Fan 1 Control Circuit Malfunction" },
            { "P0481", "Cooling Fan 2 Control Circuit Malfunction" },
            { "P0482", "Cooling Fan 3 Control Circuit Malfunction" },
            { "P0483", "Cooling Fan Rationality Check Malfunction" },
            { "P0484", "Cooling Fan Circuit Over Current" },
            { "P0485", "Cooling Fan Power/Ground Circuit Malfunction" },
            { "P0500", "Vehicle Speed Sensor Malfunction" },
            { "P0501", "Vehicle Speed Sensor Range/Performance" },
            { "P0502", "Vehicle Speed Sensor Circuit Low Input" },
            { "P0503", "Vehicle Speed Sensor Intermittent/Erratic/High" },
            { "P0505", "Idle Control System Malfunction" },
            { "P0506", "Idle Control System RPM Lower Than Expected" },
            { "P0507", "Idle Control System RPM Higher Than Expected" },
            { "P0508", "Idle Control System Circuit Low" },
            { "P0509", "Idle Control System Circuit High" },
            { "P0510", "Closed Throttle Position Switch Malfunction" },
            { "P0511", "Idle Air Control Circuit" },
            { "P0512", "Starter Request Circuit" },
            { "P0513", "Incorrect Immobilizer Key" },
            { "P0514", "Battery Temperature Sensor Circuit Range/Performance" },
            { "P0515", "Battery Temperature Sensor Circuit" },
            { "P0516", "Battery Temperature Sensor Circuit Low" },
            { "P0517", "Battery Temperature Sensor Circuit High" },
            { "P0519", "Idle Control System Performance" },
            { "P0520", "Engine Oil Pressure Sensor/Switch Circuit Malfunction" },
            { "P0521", "Engine Oil Pressure Sensor/Switch Range/Performance" },
            { "P0522", "Engine Oil Pressure Sensor/Switch Low Voltage" },
            { "P0523", "Engine Oil Pressure Sensor/Switch High Voltage" },
            { "P0524", "Engine Oil Pressure Too Low" },
            { "P0530", "A/C Refrigerant Pressure Sensor Circuit Malfunction" },
            { "P0531", "A/C Refrigerant Pressure Sensor Circuit Range/Performance" },
            { "P0532", "A/C Refrigerant Pressure Sensor Circuit Low Input" },
            { "P0533", "A/C Refrigerant Pressure Sensor Circuit High Input" },
            { "P0534", "Air Conditioner Refrigerant Charge Loss" },
            { "P0540", "Intake Air Heater A Circuit" },
            { "P0545", "Exhaust Gas Temperature Sensor Circuit Low (Bank 1 Sensor 1)" },
            { "P0546", "Exhaust Gas Temperature Sensor Circuit High (Bank 1 Sensor 1)" },
            { "P0550", "Power Steering Pressure Sensor/Switch Circuit Malfunction" },
            { "P0551", "Power Steering Pressure Sensor/Switch Circuit Range/Performance" },
            { "P0552", "Power Steering Pressure Sensor/Switch Circuit Low Input" },
            { "P0553", "Power Steering Pressure Sensor/Switch Circuit High Input" },
            { "P0560", "System Voltage Malfunction" },
            { "P0561", "System Voltage Unstable" },
            { "P0562", "System Voltage Low" },
            { "P0563", "System Voltage High" },
            { "P0564", "Cruise Control Multi-Function Input A Circuit" },
            { "P0571", "Cruise Control/Brake Switch A Circuit Malfunction" },
            { "P0572", "Cruise Control/Brake Switch A Circuit Low" },
            { "P0573", "Cruise Control/Brake Switch A Circuit High" },
            { "P0574", "Cruise Control System - Vehicle Speed Too High" },
            { "P0575", "Cruise Control Input Circuit" },
            { "P0576", "Cruise Control Input Circuit Low" },
            { "P0577", "Cruise Control Input Circuit High" },
            { "P0578", "Cruise Control Multi-Function Input A Circuit Stuck" },
            { "P0579", "Cruise Control Multi-Function Input A Circuit Range/Performance" },
            { "P0580", "Cruise Control Multi-Function Input A Circuit Low" },
            { "P0581", "Cruise Control Multi-Function Input A Circuit High" },
            { "P0582", "Cruise Control Vacuum Control Circuit Open" },
            { "P0600", "Serial Communication Link Malfunction" },
            { "P0601", "Internal Control Module Memory Check Sum Error" },
            { "P0602", "Control Module Programming Error" },
            { "P0603", "Internal Control Module Keep Alive Memory (KAM) Error" },
            { "P0604", "Internal Control Module Random Access Memory (RAM) Error" },
            { "P0605", "Internal Control Module Read Only Memory (ROM) Error" },
            { "P0606", "PCM Processor Fault" },
            { "P0607", "Control Module Performance" },
            { "P0608", "Control Module VSS Output A Malfunction" },
            { "P0609", "Control Module VSS Output B Malfunction" },
            { "P0610", "Control Module Vehicle Options Error" },
            { "P0611", "Fuel Injector Control Module Performance" },
            { "P0612", "Fuel Injector Control Module Relay Control" },
            { "P0613", "TCM Processor" },
            { "P0614", "ECM/TCM Incompatible" },
            { "P0615", "Starter Relay Circuit" },
            { "P0616", "Starter Relay Circuit Low" },
            { "P0617", "Starter Relay Circuit High" },
            { "P0618", "Alternative Fuel Control Module KAM Error" },
            { "P0619", "Alternative Fuel Control Module RAM/ROM Error" },
            { "P0620", "Generator Control Circuit Malfunction" },
            { "P0621", "Generator Lamp/L Terminal Circuit Malfunction" },
            { "P0622", "Generator Field/F Terminal Circuit Malfunction" },
            { "P0625", "Generator Field Terminal Circuit Low" },
            { "P0626", "Generator Field Terminal Circuit High" },
            { "P0627", "Fuel Pump A Control Circuit/Open" },
            { "P0628", "Fuel Pump A Control Circuit Low" },
            { "P0629", "Fuel Pump A Control Circuit High" },
            { "P0630", "VIN Not Programmed or Incompatible - ECM/PCM" },
            { "P0638", "Throttle Actuator Control Range/Performance (Bank 1)" },
            { "P0639", "Throttle Actuator Control Range/Performance (Bank 2)" },
            { "P0650", "Malfunction Indicator Lamp (MIL) Control Circuit Malfunction" },
            { "P0651", "Sensor Reference Voltage A Circuit Open" },
            { "P0652", "Sensor Reference Voltage A Circuit Low" },
            { "P0653", "Sensor Reference Voltage A Circuit High" },
            { "P0654", "Engine RPM Output Circuit Malfunction" },
            { "P0655", "Engine Hot Lamp Output Control Circuit Malfunction" },
            { "P0656", "Fuel Level Output Circuit Malfunction" },
            { "P0657", "Actuator Supply Voltage A Circuit/Open" },
            { "P0658", "Actuator Supply Voltage A Circuit Low" },
            { "P0659", "Actuator Supply Voltage A Circuit High" },
            { "P0660", "Intake Manifold Tuning Valve Control Circuit/Open (Bank 1)" },
            { "P0661", "Intake Manifold Tuning Valve Control Circuit Low (Bank 1)" },
            { "P0662", "Intake Manifold Tuning Valve Control Circuit High (Bank 1)" },
            { "P0663", "Intake Manifold Tuning Valve Control Circuit/Open (Bank 2)" },
            { "P0664", "Intake Manifold Tuning Valve Control Circuit Low (Bank 2)" },
            { "P0665", "Intake Manifold Tuning Valve Control Circuit High (Bank 2)" },
            { "P0670", "Glow Plug Module Control Circuit" },
            { "P0671", "Cylinder 1 Glow Plug Circuit" },
            { "P0672", "Cylinder 2 Glow Plug Circuit" },
            { "P0673", "Cylinder 3 Glow Plug Circuit" },
            { "P0674", "Cylinder 4 Glow Plug Circuit" },
            { "P0675", "Cylinder 5 Glow Plug Circuit" },
            { "P0676", "Cylinder 6 Glow Plug Circuit" },
            { "P0677", "Cylinder 7 Glow Plug Circuit" },
            { "P0678", "Cylinder 8 Glow Plug Circuit" },
            { "P0680", "Glow Plug Control Module to ECM Communication Circuit" },
            { "P0685", "ECM/PCM Power Relay Control Circuit Open" },
            { "P0686", "ECM/PCM Power Relay Control Circuit Low" },
            { "P0687", "ECM/PCM Power Relay Control Circuit High" },
            { "P0688", "ECM/PCM Power Relay Sense Circuit Open" },
            { "P0689", "ECM/PCM Power Relay Sense Circuit Low" },
            { "P0690", "ECM/PCM Power Relay Sense Circuit High" },
            { "P0691", "Cooling Fan 1 Control Circuit Low" },
            { "P0692", "Cooling Fan 1 Control Circuit High" },
            { "P0693", "Cooling Fan 2 Control Circuit Low" },
            { "P0694", "Cooling Fan 2 Control Circuit High" },
            { "P0695", "Cooling Fan 3 Control Circuit Low" },
            { "P0696", "Cooling Fan 3 Control Circuit High" },
            { "P0697", "Sensor Reference Voltage C Circuit/Open" },
            { "P0698", "Sensor Reference Voltage C Circuit Low" },
            { "P0699", "Sensor Reference Voltage C Circuit High" },
            { "P0700", "Transmission Control System (MIL Request)" },
            { "P0701", "Transmission Control System Range/Performance" },
            { "P0702", "Transmission Control System Electrical" },
            { "P0703", "Torque Converter/Brake Switch B Circuit Malfunction" },
            { "P0704", "Clutch Switch Input Circuit Malfunction" },
            { "P0705", "Transmission Range Sensor Circuit Malfunction (PRNDL Input)" },
            { "P0706", "Transmission Range Sensor Circuit Range/Performance" },
            { "P0707", "Transmission Range Sensor Circuit Low Input" },
            { "P0708", "Transmission Range Sensor Circuit High Input" },
            { "P0709", "Transmission Range Sensor Circuit Intermittent" },
            { "P0710", "Transmission Fluid Temperature Sensor Circuit Malfunction" },
            { "P0711", "Transmission Fluid Temperature Sensor Circuit Range/Performance" },
            { "P0712", "Transmission Fluid Temperature Sensor Circuit Low Input" },
            { "P0713", "Transmission Fluid Temperature Sensor Circuit High Input" },
            { "P0714", "Transmission Fluid Temperature Sensor Circuit Intermittent" },
            { "P0715", "Input/Turbine Speed Sensor Circuit Malfunction" },
            { "P0716", "Input/Turbine Speed Sensor Circuit Range/Performance" },
            { "P0717", "Input/Turbine Speed Sensor Circuit No Signal" },
            { "P0718", "Input/Turbine Speed Sensor Circuit Intermittent" },
            { "P0719", "Torque Converter/Brake Switch B Circuit Low" },
            { "P0720", "Output Speed Sensor Circuit Malfunction" },
            { "P0721", "Output Speed Sensor Circuit Range/Performance" },
            { "P0722", "Output Speed Sensor Circuit No Signal" },
            { "P0723", "Output Speed Sensor Circuit Intermittent" },
            { "P0724", "Torque Converter/Brake Switch B Circuit High" },
            { "P0725", "Engine Speed Input Circuit Malfunction" },
            { "P0726", "Engine Speed Input Circuit Range/Performance" },
            { "P0727", "Engine Speed Input Circuit No Signal" },
            { "P0728", "Engine Speed Input Circuit Intermittent" },
            { "P0730", "Incorrect Gear Ratio" },
            { "P0731", "Gear 1 Incorrect Ratio" },
            { "P0732", "Gear 2 Incorrect Ratio" },
            { "P0733", "Gear 3 Incorrect Ratio" },
            { "P0734", "Gear 4 Incorrect Ratio" },
            { "P0735", "Gear 5 Incorrect Ratio" },
            { "P0736", "Reverse Incorrect Ratio" },
            { "P0740", "Torque Converter Clutch Circuit Malfunction" },
            { "P0741", "Torque Converter Clutch Circuit Performance or Stuck Off" },
            { "P0742", "Torque Converter Clutch Circuit Stuck On" },
            { "P0743", "Torque Converter Clutch Circuit Electrical" },
            { "P0744", "Torque Converter Clutch Circuit Intermittent" },
            { "P0745", "Pressure Control Solenoid A Malfunction" },
            { "P0746", "Pressure Control Solenoid A Performance or Stuck Off" },
            { "P0747", "Pressure Control Solenoid A Stuck On" },
            { "P0748", "Pressure Control Solenoid A Electrical" },
            { "P0749", "Pressure Control Solenoid A Intermittent" },
            { "P0750", "Shift Solenoid A Malfunction" },
            { "P0751", "Shift Solenoid A Performance or Stuck Off" },
            { "P0752", "Shift Solenoid A Stuck On" },
            { "P0753", "Shift Solenoid A Electrical" },
            { "P0754", "Shift Solenoid A Intermittent" },
            { "P0755", "Shift Solenoid B Malfunction" },
            { "P0756", "Shift Solenoid B Performance or Stuck Off" },
            { "P0757", "Shift Solenoid B Stuck On" },
            { "P0758", "Shift Solenoid B Electrical" },
            { "P0759", "Shift Solenoid B Intermittent" },
            { "P0760", "Shift Solenoid C Malfunction" },
            { "P0761", "Shift Solenoid C Performance or Stuck Off" },
            { "P0762", "Shift Solenoid C Stuck On" },
            { "P0763", "Shift Solenoid C Electrical" },
            { "P0764", "Shift Solenoid C Intermittent" },
            { "P0765", "Shift Solenoid D Malfunction" },
            { "P0766", "Shift Solenoid D Performance or Stuck Off" },
            { "P0767", "Shift Solenoid D Stuck On" },
            { "P0768", "Shift Solenoid D Electrical" },
            { "P0769", "Shift Solenoid D Intermittent" },
            { "P0770", "Shift Solenoid E Malfunction" },
            { "P0771", "Shift Solenoid E Performance or Stuck Off" },
            { "P0772", "Shift Solenoid E Stuck On" },
            { "P0773", "Shift Solenoid E Electrical" },
            { "P0774", "Shift Solenoid E Intermittent" },
            { "P0780", "Shift Malfunction" },
            { "P0781", "1-2 Shift Malfunction" },
            { "P0782", "2-3 Shift Malfunction" },
            { "P0783", "3-4 Shift Malfunction" },
            { "P0784", "4-5 Shift Malfunction" },
            { "P0785", "Shift/Timing Solenoid Malfunction" },
            { "P0800", "Transfer Case Control System (MIL Request)" },
            { "P0801", "Reverse Inhibit Control Circuit Malfunction" },
            { "P0802", "Transmission Control System MIL Request Circuit/Open" },
            { "P0803", "1-4 Upshift (Skip Shift) Solenoid Control Circuit Malfunction" },
            { "P0804", "1-4 Upshift (Skip Shift) Lamp Control Circuit Malfunction" },
            { "P0805", "Clutch Position Sensor Circuit" },
            { "P0806", "Clutch Position Sensor Circuit Range/Performance" },
            { "P0807", "Clutch Position Sensor Circuit Low" },
            { "P0808", "Clutch Position Sensor Circuit High" },
            { "P0809", "Clutch Position Sensor Circuit Intermittent" },
            { "P0810", "Clutch Position Control Error" },
            { "P0811", "Excessive Clutch Slippage" },
            { "P0812", "Reverse Input Circuit" },
            { "P0813", "Reverse Output Circuit" },
            { "P0814", "Transmission Range Display Circuit" },
            { "P0815", "Upshift Switch Circuit" },
            { "P0816", "Downshift Switch Circuit" },
            { "P0817", "Starter Disable Circuit" },
            { "P0818", "Driveline Disconnect Switch Input Circuit" },
            { "P0819", "Up and Down Shift Switch to Transmission Range Correlation" },
            { "P0826", "Up and Down Shift Switch Circuit" },
            // Body codes
            { "B0001", "Driver Frontal Stage 1 Deployment Control" },
            { "B0002", "Driver Frontal Stage 2 Deployment Control" },
            { "B0003", "Driver Frontal Stage 1 Squib Resistance Low" },
            { "B0004", "Driver Frontal Stage 1 Squib Resistance High" },
            { "B0005", "Driver Frontal Stage 2 Squib Resistance Low" },
            { "B0006", "Driver Frontal Stage 2 Squib Resistance High" },
            { "B0007", "Driver Side Stage 1 Deployment Control" },
            { "B0008", "Driver Side Stage 2 Deployment Control" },
            { "B0009", "Driver Side Stage 1 Squib Resistance Low" },
            { "B0010", "Driver Frontal Airbag Deployment Loop Resistance Low" },
            { "B0011", "Driver Frontal Airbag Deployment Loop Open" },
            { "B0012", "Driver Frontal Airbag Deployment Loop Short to Ground" },
            { "B0013", "Driver Frontal Airbag Deployment Loop Short to Voltage" },
            { "B0014", "Passenger Frontal Airbag Deployment Loop Resistance Low" },
            { "B0015", "Passenger Frontal Airbag Deployment Loop Open" },
            { "B0016", "Passenger Frontal Airbag Deployment Loop Short to Ground" },
            { "B0017", "Passenger Frontal Airbag Deployment Loop Short to Voltage" },
            { "B0051", "Driver Side Curtain Airbag Deployment Loop Resistance Low" },
            { "B0052", "Driver Side Curtain Airbag Deployment Loop Open" },
            { "B0053", "Driver Side Curtain Airbag Deployment Loop Short to Ground" },
            { "B0054", "Driver Side Curtain Airbag Deployment Loop Short to Voltage" },
            { "B0070", "Passenger Side Curtain Airbag Deployment Loop Resistance Low" },
            { "B0071", "Passenger Side Curtain Airbag Deployment Loop Open" },
            { "B0081", "Driver Knee Airbag Deployment Loop Resistance Low" },
            { "B0082", "Driver Knee Airbag Deployment Loop Open" },
            { "B1000", "ECU Malfunction" },
            { "B1001", "Option Configuration Error" },
            { "B1004", "Close Header Reference Voltage Out of Range" },
            { "B1005", "Close Header Reference Voltage Out of Range Low" },
            { "B1006", "Close Header Reference Voltage Out of Range High" },
            { "B1009", "Keep Alive Memory Power Feed Circuit" },
            // Chassis codes
            { "C0001", "ABS Wheel Speed Sensor Right Front Circuit" },
            { "C0002", "ABS Wheel Speed Sensor Right Front Circuit Range/Performance" },
            { "C0005", "ABS Wheel Speed Sensor Left Front Circuit" },
            { "C0006", "ABS Wheel Speed Sensor Left Front Circuit Range/Performance" },
            { "C0009", "ABS Wheel Speed Sensor Right Rear Circuit" },
            { "C0010", "ABS Wheel Speed Sensor Right Rear Circuit Range/Performance" },
            { "C0013", "ABS Wheel Speed Sensor Left Rear Circuit" },
            { "C0014", "ABS Wheel Speed Sensor Left Rear Circuit Range/Performance" },
            { "C0020", "ABS Wheel Speed Sensor RF Circuit" },
            { "C0021", "ABS Wheel Speed Sensor RF Circuit Range/Performance" },
            { "C0025", "ABS Wheel Speed Sensor LF Circuit" },
            { "C0026", "ABS Wheel Speed Sensor LF Circuit Range/Performance" },
            { "C0029", "ABS Wheel Speed Sensor RR Circuit" },
            { "C0030", "ABS Wheel Speed Sensor RR Circuit Range/Performance" },
            { "C0031", "ABS Wheel Speed Sensor LR Circuit Malfunction" },
            { "C0032", "ABS Wheel Speed Sensor LR Circuit Range/Performance" },
            { "C0033", "ABS Wheel Speed Sensor RF Erratic Performance" },
            { "C0034", "ABS Wheel Speed Sensor RF Intermittent" },
            { "C0035", "ABS Wheel Speed Sensor LF Erratic Performance" },
            { "C0036", "ABS Wheel Speed Sensor LF Intermittent" },
            { "C0040", "Right Front Wheel Speed Sensor Circuit Fault" },
            { "C0041", "Right Front Wheel Speed Sensor Circuit Range/Performance" },
            { "C0045", "Left Front Wheel Speed Sensor Circuit Fault" },
            { "C0046", "Left Front Wheel Speed Sensor Circuit Range/Performance" },
            { "C0050", "Right Rear Wheel Speed Sensor Circuit Fault" },
            { "C0051", "Right Rear Wheel Speed Sensor Circuit Range/Performance" },
            { "C0055", "Left Rear Wheel Speed Sensor Circuit Fault" },
            { "C0056", "Left Rear Wheel Speed Sensor Circuit Range/Performance" },
            { "C0060", "Left Front Solenoid Circuit Fault" },
            { "C0061", "Left Front Solenoid Circuit Range/Performance" },
            { "C0063", "Right Front Solenoid Circuit Fault" },
            { "C0064", "Right Front Solenoid Circuit Range/Performance" },
            { "C0066", "Left Rear Solenoid Circuit Fault" },
            { "C0067", "Left Rear Solenoid Circuit Range/Performance" },
            { "C0069", "Right Rear Solenoid Circuit Fault" },
            { "C0070", "Right Rear Solenoid Circuit Range/Performance" },
            { "C0110", "Pump Motor Circuit Fault" },
            { "C0111", "Pump Motor Circuit Range/Performance" },
            { "C0113", "Pump Motor Circuit Low" },
            { "C0114", "Pump Motor Circuit High" },
            { "C0121", "Valve Relay Circuit Fault" },
            { "C0122", "Valve Relay Circuit Range/Performance" },
            { "C0131", "Anti-Lock Brake System Pressure Sensor Circuit Fault" },
            { "C0136", "Brake Pressure Sensor Circuit Fault" },
            { "C0141", "Left Front ABS Solenoid 1 Circuit Low" },
            { "C0142", "Left Front ABS Solenoid 1 Circuit High" },
            { "C0145", "Left Front ABS Solenoid 2 Circuit Low" },
            { "C0146", "Left Front ABS Solenoid 2 Circuit High" },
            { "C0151", "Right Front ABS Solenoid 1 Circuit Low" },
            { "C0152", "Right Front ABS Solenoid 1 Circuit High" },
            { "C0155", "Right Front ABS Solenoid 2 Circuit Low" },
            { "C0156", "Right Front ABS Solenoid 2 Circuit High" },
            { "C0161", "ABS/TCS Brake Switch Circuit Fault" },
            { "C0162", "ABS/TCS Brake Switch Circuit Range/Performance" },
            { "C0186", "Lateral Accelerometer Sensor Circuit Fault" },
            { "C0187", "Lateral Accelerometer Sensor Circuit Range/Performance" },
            { "C0196", "Yaw Rate Sensor Circuit Fault" },
            { "C0197", "Yaw Rate Sensor Circuit Range/Performance" },
            { "C0200", "Right Front Wheel Speed Sensor Circuit Open/Short" },
            { "C0205", "Left Front Wheel Speed Sensor Circuit Open/Short" },
            { "C0210", "Right Rear Wheel Speed Sensor Circuit Open/Short" },
            { "C0215", "Left Rear Wheel Speed Sensor Circuit Open/Short" },
            { "C0221", "Right Front Wheel Speed Sensor Signal Erratic" },
            { "C0222", "Right Front Wheel Speed Sensor Signal Always Zero" },
            { "C0223", "Right Front Wheel Speed Sensor Abnormal" },
            { "C0225", "Left Front Wheel Speed Sensor Signal Erratic" },
            { "C0226", "Left Front Wheel Speed Sensor Signal Always Zero" },
            { "C0229", "Right Rear Wheel Speed Sensor Signal Erratic" },
            { "C0230", "Right Rear Wheel Speed Sensor Signal Always Zero" },
            { "C0235", "Left Rear Wheel Speed Sensor Signal Erratic" },
            { "C0236", "Left Rear Wheel Speed Sensor Signal Always Zero" },
            { "C0240", "EBCM Power Relay Circuit Fault" },
            { "C0241", "EBCM Control Valve Circuit Fault" },
            { "C0245", "Wheel Speed Sensor Frequency Error" },
            { "C0246", "Wheel Speed Sensor Coherency Error" },
            { "C0252", "Active Suspension Control Module Error" },
            { "C0253", "Centering Error" },
            { "C0254", "Actuator Circuit Error" },
            { "C0255", "Shock Absorber Position Sensor Circuit Error" },
            { "C0261", "LF Inlet Valve Solenoid Circuit" },
            { "C0262", "LF Outlet Valve Solenoid Circuit" },
            { "C0263", "RF Inlet Valve Solenoid Circuit" },
            { "C0264", "RF Outlet Valve Solenoid Circuit" },
            { "C0265", "EBCM Relay Circuit Open" },
            { "C0266", "EBCM Relay Circuit Shorted to Ground" },
            { "C0267", "Pump Motor Circuit Open/Shorted" },
            { "C0268", "Pump Motor Stalled" },
            // Network/Communication codes
            { "U0001", "High Speed CAN Communication Bus" },
            { "U0002", "High Speed CAN Communication Bus Performance" },
            { "U0003", "High Speed CAN Communication Bus Open" },
            { "U0004", "High Speed CAN Communication Bus Short to Ground" },
            { "U0005", "High Speed CAN Communication Bus Short to Battery" },
            { "U0006", "Medium Speed CAN Communication Bus" },
            { "U0007", "Medium Speed CAN Communication Bus Performance" },
            { "U0008", "Medium Speed CAN Communication Bus Open" },
            { "U0009", "Medium Speed CAN Communication Bus Short to Ground" },
            { "U0010", "Medium Speed CAN Communication Bus Short to Battery" },
            { "U0011", "Low Speed CAN Communication Bus" },
            { "U0014", "Sub Bus A Communication" },
            { "U0020", "LIN Bus A" },
            { "U0021", "LIN Bus A Performance" },
            { "U0022", "LIN Bus A Open" },
            { "U0023", "LIN Bus A Short to Ground" },
            { "U0024", "LIN Bus A Short to Battery" },
            { "U0025", "LIN Bus B" },
            { "U0031", "LIN Bus C" },
            { "U0037", "LIN Bus D" },
            { "U0043", "LIN Bus E" },
            { "U0049", "LIN Bus F" },
            { "U0073", "Control Module Communication Bus Off" },
            { "U0100", "Lost Communication With ECM/PCM" },
            { "U0101", "Lost Communication With TCM" },
            { "U0102", "Lost Communication With Transfer Case Control Module" },
            { "U0103", "Lost Communication With Gear Shift Module" },
            { "U0104", "Lost Communication With Cruise Control Module" },
            { "U0105", "Lost Communication With Fuel Injector Control Module" },
            { "U0106", "Lost Communication With Glow Plug Control Module" },
            { "U0107", "Lost Communication With Throttle Actuator Control Module" },
            { "U0108", "Lost Communication With Alternative Fuel Control Module" },
            { "U0109", "Lost Communication With Fuel Pump Control Module" },
            { "U0110", "Lost Communication With Drive Motor Control Module" },
            { "U0111", "Lost Communication With Battery Energy Control Module A" },
            { "U0112", "Lost Communication With Battery Energy Control Module B" },
            { "U0113", "Lost Communication With Emissions Critical Control Information" },
            { "U0114", "Lost Communication With Four-Wheel Drive Clutch Control Module" },
            { "U0121", "Lost Communication With Anti-Lock Brake System (ABS) Control Module" },
            { "U0122", "Lost Communication With Vehicle Dynamics Control Module" },
            { "U0123", "Lost Communication With Yaw Rate Sensor Module" },
            { "U0124", "Lost Communication With Lateral Acceleration Sensor Module" },
            { "U0125", "Lost Communication With Multi-Axis Acceleration Sensor Module" },
            { "U0126", "Lost Communication With Steering Angle Sensor Module" },
            { "U0127", "Lost Communication With Tire Pressure Monitor Module" },
            { "U0128", "Lost Communication With Park Brake Control Module" },
            { "U0129", "Lost Communication With Brake System Control Module" },
            { "U0130", "Lost Communication With Ride Level Control Module" },
            { "U0131", "Lost Communication With Power Steering Control Module" },
            { "U0132", "Lost Communication With Ride Height Control Module" },
            { "U0140", "Lost Communication With Body Control Module" },
            { "U0141", "Lost Communication With Body Control Module A" },
            { "U0142", "Lost Communication With Body Control Module B" },
            { "U0143", "Lost Communication With Body Control Module C" },
            { "U0144", "Lost Communication With Body Control Module D" },
            { "U0145", "Lost Communication With Body Control Module E" },
            { "U0146", "Lost Communication With Gateway A" },
            { "U0147", "Lost Communication With Gateway B" },
            { "U0151", "Lost Communication With Restraints Control Module" },
            { "U0155", "Lost Communication With Instrument Panel Cluster (IPC) Control Module" },
            { "U0156", "Lost Communication With Information Center A" },
            { "U0157", "Lost Communication With Information Center B" },
            { "U0158", "Lost Communication With Head Up Display" },
            { "U0159", "Lost Communication With Parking Assist Control Module" },
            { "U0160", "Lost Communication With Audible Alert Control Module" },
            { "U0164", "Lost Communication With HVAC Control Module" },
            { "U0165", "Lost Communication With HVAC Control Module B" },
            { "U0168", "Lost Communication With Vehicle Security Control Module" },
            { "U0169", "Lost Communication With Sunroof Control Module" },
            { "U0170", "Lost Communication With Restraints System Sensor A" },
            { "U0171", "Lost Communication With Restraints System Sensor B" },
            { "U0174", "Lost Communication With Remote Climate Control Module" },
            { "U0175", "Lost Communication With Climate Control Rear Zone Module" },
            { "U0176", "Lost Communication With Road Surface Condition Module" },
            { "U0177", "Lost Communication With Road Surface Condition Sensor" },
            { "U0178", "Lost Communication With Road Friction Module" },
            { "U0184", "Lost Communication With Radio" },
            { "U0185", "Lost Communication With Antenna Control Module" },
            { "U0186", "Lost Communication With Audio Amplifier" },
            { "U0187", "Lost Communication With Digital Disc Player/Changer (Module A)" },
            { "U0188", "Lost Communication With Digital Disc Player/Changer (Module B)" },
            { "U0189", "Lost Communication With Digital Disc Player/Changer (Module C)" },
            { "U0190", "Lost Communication With Digital Disc Player/Changer (Module D)" },
            { "U0191", "Lost Communication With Television" },
            { "U0192", "Lost Communication With Personal Communication Device (Module A)" },
            { "U0193", "Lost Communication With Digital Audio Control Module A" },
            { "U0194", "Lost Communication With Digital Audio Control Module B" },
            { "U0195", "Lost Communication With Subscription Entertainment Receiver" },
            { "U0196", "Lost Communication With Rear Seat Entertainment Module A" },
            { "U0197", "Lost Communication With Telephone Control Module A" },
            { "U0198", "Lost Communication With Telematic Control Module" },
            { "U0200", "Lost Communication With Door Control Module A" },
            { "U0201", "Lost Communication With Door Control Module B" },
            { "U0202", "Lost Communication With Door Control Module C" },
            { "U0203", "Lost Communication With Door Control Module D" },
            { "U0204", "Lost Communication With Door Control Module E" },
            { "U0205", "Lost Communication With Door Control Module F" },
            { "U0206", "Lost Communication With Folding Top Control Module" },
            { "U0207", "Lost Communication With Moveable Roof Control Module" },
            { "U0208", "Lost Communication With Seat Control Module A" },
            { "U0209", "Lost Communication With Seat Control Module B" },
            { "U0210", "Lost Communication With Seat Control Module C" },
            { "U0211", "Lost Communication With Seat Control Module D" },
            { "U0212", "Lost Communication With Steering Column Control Module" },
            { "U0213", "Lost Communication With Mirror Control Module" },
            { "U0214", "Lost Communication With Remote Function Actuator" },
            { "U0215", "Lost Communication With Digital EGR Control Module" },
            { "U0216", "Lost Communication With Fuel Sender Module" },
            { "U0217", "Lost Communication With Rear Spoiler Control Module" },
            { "U0218", "Lost Communication With Message Display Controller" },
            { "U0219", "Lost Communication With Steering Wheel Control Module" },
            { "U0220", "Lost Communication With Wiper Control Module" },
            { "U0221", "Lost Communication With Window Control Module A" },
            { "U0222", "Lost Communication With Window Control Module B" },
            { "U0223", "Lost Communication With Exterior Lighting Control Module A" },
            { "U0224", "Lost Communication With Exterior Lighting Control Module B" },
            { "U0225", "Lost Communication With Interior Lighting Control Module" },
            { "U0226", "Lost Communication With Trailer Module" },
            { "U0228", "Lost Communication With Battery Charger Module" },
            { "U0229", "Lost Communication With Passive Entry Control Module" },
            { "U0230", "Lost Communication With Running Boards Control Module" },
            { "U0231", "Lost Communication With Rain Sensing Module" },
            { "U0232", "Lost Communication With Side Object Detection Control Module A" },
            { "U0233", "Lost Communication With Side Object Detection Control Module B" },
            { "U0234", "Lost Communication With Forward Collision Avoidance Module" },
            { "U0235", "Lost Communication With Cruise Control Front Distance Range Sensor" },
            { "U0237", "Lost Communication With Garage Door Opener Control Module" },
            { "U0238", "Lost Communication With Steering Effort Control Module" },
            { "U0239", "Lost Communication With Single Board Engine Controller A" },
            { "U0240", "Lost Communication With Single Board Engine Controller B" },
            { "U0300", "Internal Control Module Software Incompatibility" },
            { "U0301", "Software Incompatibility with ECM/PCM" },
            { "U0302", "Software Incompatibility with TCM" },
            { "U0303", "Software Incompatibility with Transfer Case Control Module" },
            { "U0304", "Software Incompatibility with Gear Shift Module" },
            { "U0306", "Software Incompatibility with Fuel Injector Control Module" },
            { "U0307", "Software Incompatibility with Glow Plug Control Module" },
            { "U0308", "Software Incompatibility with Throttle Actuator Control Module" },
            { "U0310", "Software Incompatibility with Drive Motor Control Module" },
            { "U0320", "Software Incompatibility with Anti-Lock Brake System (ABS) Control Module" },
            { "U0322", "Software Incompatibility with Body Control Module" },
            { "U0324", "Software Incompatibility with HVAC Control Module" },
            { "U0325", "Software Incompatibility with Auxiliary Heater Control Module" },
            { "U0327", "Software Incompatibility with Vehicle Security Control Module" },
            { "U0328", "Software Incompatibility with Steering Angle Sensor Module" },
            { "U0329", "Software Incompatibility with Steering Column Control Module" },
            { "U0333", "Software Incompatibility with Front Sensors Airbag" },
            { "U0335", "Software Incompatibility with Instrument Panel Cluster (IPC) Control Module" },
            { "U0336", "Software Incompatibility with Radio" },
            { "U0338", "Software Incompatibility with Door Control Module A" },
            { "U0339", "Software Incompatibility with Door Control Module B" },
        };

        public static string GetDescription(string code)
        {
            if (string.IsNullOrWhiteSpace(code)) return "Unknown Fault Code";
            var upper = code.ToUpperInvariant().Trim();
            return _descriptions.TryGetValue(upper, out var desc) ? desc : $"Manufacturer Specific or Unknown Code ({upper})";
        }
    }
}
